### ISSUE TITLE
Not an issue, more of a question

### ISSUE THREAD

**Issue by fluxxus** [okydk/basegrid#1]
I am quite comfortable with flexbox(been using from the early implementations), but I still haven't found time to properly learn CSS grid.

I've read(skimmed) a few articles, just to gain some understanding how it works. But that is it.

Then I stumbled upon your nice mix of grid and custom properties, and that got my attention.

My question is are there any downsides to just using your library compared to writing layouts with the whole grid spec at disposal.

Are there some layouts/stuff that can't be just built by using your library, or it will cover for most use cases?

**Comment by okydk** [comment]
Hi Mirko, glad you like it!

I find the CSS-grid spec quite confusing and therefore created this lib as an abstraction to use in all my projects. So far it has covered all my use-cases, and when extra is needed the CSS can just be extended or overwritten as it just uses CSS-grid! 😀

I will add new features as I require myself, but am all ears if you need any specific functionality.

**Comment by fluxxus** [comment]
Hi, thanks for clearing things up :) You've really nailed it in a few lines of code. 

As for additional functionality, I've seen lately a few grid articles about leaving empty cells(and styling them) to create some visual interest.

Not sure if that is possible with your lib, although I believe it is not something that one can't live without. 

P. S. The demo page is not looking good on mobile, text overflows the columns, maybe to show a way how to rearrange the layout for smaller screens? 

Also, it would be nice to recreate a few layouts from let's say Grid by example site, and have those layouts in the docs for people that want to see how this works in so called real life scenarios. 

Those are the things that come to my mind now, for anything else I need to start building stuff!

**Comment by okydk** [comment]
That's where `--x` and `--y` comes handy! You can place sections completely independent of the general flow. With this you can create all the white-space you need. Another approach would be to put some empty sections in with certain heights. Little tip: Use a fixed grid at least while building.

Thanks for the heads up! Will fix the mobile site asap, and also include some more detailed examples in the repo. :)

**Comment by fluxxus** [comment]
Great! Appreciate the tip(s) :)

Looking forward to more detailed examples!!
